name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths-ignore:
      - helm/**
      - .github/workflows/ci-helm-workflow.yml
      - 'metrics/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
